import Navigation from '@/components/Navigation'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from 'next/image'
import Link from 'next/link'
import NavigationLink from '@/components/NavigationLink'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="container mx-auto my-8">
          <div className="mx-16">
            <Navigation>
              <NavigationLink href="/">Home</NavigationLink>
              <NavigationLink href="/about">About</NavigationLink>
              <NavigationLink href="/service">Service</NavigationLink>
              <Link href="/" className="-my-1 mx-auto px-4">
                <Image alt="Logo" src="/logo.svg" height={40} width={84} />
              </Link>
              <NavigationLink href="/resume">Resume</NavigationLink>
              <NavigationLink href="/portfolio">Portfolio</NavigationLink>
              <NavigationLink href="/contact">Contact</NavigationLink>
            </Navigation>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
