import Footer from '@/partials/Footer'
import FooterContact from '@/partials/FooterContact'
import RootNavigation from '@/partials/RootNavigation'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'

const poppins = Poppins({ subsets: ['latin'], weight: ['400', '600'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export type RootLayoutProps = {
  modal: React.ReactNode
  children: React.ReactNode
}

const RootLayout = ({ modal, children }: RootLayoutProps) => {
  return (
    <html lang="en">
      <body className={`min-h-screen ${poppins.className}`}>
        <div className="mx-auto max-w-[1440px] px-16">
          <RootNavigation />
          {children}
          <Footer>
            <FooterContact />
          </Footer>
        </div>
        {modal}
      </body>
    </html>
  )
}

export default RootLayout
